import Foundation

/// One thing worth saying, plus the measurement that licenses saying it.
///
/// The split exists because a coach and an auditor want different things from
/// the same fact. `text` is what a climber reads — plain language, no figures.
/// `evidence` is generated by code and reached by tapping, so nothing is hidden,
/// it is only moved out of the way.
public struct AnalysisNote: Sendable, Codable, Hashable, Identifiable {
    public var text: String
    /// Generated by code, never by a model. Carries the figures, units and
    /// confidence that `text` is standing on.
    public var evidence: String
    /// Which measurement this came from, so the UI can jump to it.
    public var metric: MetricKind?

    public var id: String { text }

    public init(text: String, evidence: String, metric: MetricKind? = nil) {
        self.text = text
        self.evidence = evidence
        self.metric = metric
    }

    /// Builds the evidence line for a delta. One place, so the format is
    /// consistent and the prose never has to carry it.
    public static func evidence(for d: MetricDelta) -> String {
        func format(_ v: Double?) -> String {
            guard let v else { return "—" }
            return d.kind.unit == "%"
                ? String(format: "%.0f%%", v * 100)
                : String(format: "%.2f %@", v, d.kind.unit)
        }
        var line = "\(d.kind.displayName): you \(format(d.attempt)), reference \(format(d.reference))"
        if let delta = d.delta {
            line += d.kind.unit == "%"
                ? String(format: " (%+.0f%%)", delta * 100)
                : String(format: " (%+.2f)", delta)
        }
        line += String(format: " · confidence %.0f%%", d.confidence * 100)
        return line
    }
}

public struct SectionAnalysis: Sendable, Codable, Hashable, Identifiable {
    public var sectionIndex: Int
    public var headline: String
    public var observations: [AnalysisNote]
    public var drill: String?
    /// Which provider produced this, so the harness can tell template output
    /// from model output at a glance.
    public var source: String
    public var warnings: [String]

    public var id: Int { sectionIndex }

    public init(
        sectionIndex: Int,
        headline: String,
        observations: [AnalysisNote],
        drill: String?,
        source: String,
        warnings: [String] = []
    ) {
        self.sectionIndex = sectionIndex
        self.headline = headline
        self.observations = observations
        self.drill = drill
        self.source = source
        self.warnings = warnings
    }

    /// Everything a reader sees as prose. Deliberately excludes `evidence` —
    /// the guards run against what is *claimed*, not against the figures code
    /// generated to back it up.
    public var allText: String {
        ([headline] + observations.map(\.text) + (drill.map { [$0] } ?? [])).joined(separator: " ")
    }
}

/// Turns computed numbers into sentences. **Never the other way round** — a
/// provider that produces a quantity is a bug.
public protocol AnalysisProvider: Sendable {
    var name: String { get }
    var isAvailable: Bool { get async }
    func analyze(_ delta: SectionDelta) async throws -> SectionAnalysis
    func analyzeFall(_ report: FallReport, sections: [SectionDelta]) async throws -> SectionAnalysis?
}

// MARK: - Guards

/// Asserts that generated text contains no number that wasn't in the input.
///
/// This is the enforcement arm of "code measures, the model narrates". A model
/// that writes "about 15cm" when it was given `0.31 body-lengths` has invented
/// a measurement, and the output is discarded rather than shown.
public enum NumberGuard {

    /// Every value a sentence may legitimately quote: the move ordinal, each
    /// metric's reference, attempt and delta, and their percentage forms.
    public static func allowedValues(for delta: SectionDelta) -> [Double] {
        var out: [Double] = [Double(delta.sectionIndex + 1)]
        for d in delta.deltas {
            for v in [d.reference, d.attempt, d.delta].compactMap({ $0 }) {
                out.append(contentsOf: [v, abs(v), v * 100, abs(v) * 100])
            }
        }
        return out
    }

    /// A quoted number counts as supported when it is within rounding distance
    /// of a computed one. Narrating "0.9" for 0.871, or "87%" for 0.8712, is
    /// what the provider is supposed to do; writing "15" when nothing near 15
    /// was computed is inventing a measurement.
    public static func isSupported(_ n: Double, allowed: [Double]) -> Bool {
        allowed.contains { abs(n - $0) <= max(0.55, abs($0) * 0.02) }
    }

    static let numberPattern = try? NSRegularExpression(pattern: #"-?\d+(?:\.\d+)?"#)

    public static func numbers(in text: String) -> [Double] {
        guard let numberPattern else { return [] }
        let range = NSRange(text.startIndex ..< text.endIndex, in: text)
        return numberPattern.matches(in: text, range: range).compactMap {
            guard let r = Range($0.range, in: text) else { return nil }
            return Double(text[r])
        }
    }

    /// Numbers present in `text` that are not derivable from `allowed`.
    public static func unsupportedNumbers(in text: String, allowed: [Double]) -> [Double] {
        numbers(in: text).filter { !isSupported($0, allowed: allowed) }
    }

    /// Numbers in generated prose, **other than the move ordinal**.
    ///
    /// Now that every figure lives in `AnalysisNote.evidence`, which code
    /// generates, prose has no legitimate reason to contain a digit at all. That
    /// turns a fuzzy tolerance check into an absolute one: anything numeric in a
    /// model's sentence is unsupported by construction, and there is nothing to
    /// tune or argue about.
    ///
    /// Move ordinals are the single exception, and they are templated in by code
    /// rather than written by the model.
    public static func straySignificantDigits(in text: String, allowingMoveOrdinals ordinals: Set<Int>) -> [Double] {
        numbers(in: text).filter { value in
            guard let ordinal = Int(exactly: value.rounded()), abs(value - value.rounded()) < 1e-9 else { return true }
            return !ordinals.contains(ordinal)
        }
    }

    /// Units that must never appear: this project has no climber profile, so a
    /// kilogram or a centimetre can only have been invented.
    public static let forbiddenUnits = ["kg", "kilogram", "lb", "pound", "cm", "centimet", "metre", "meter", "inch", "foot of", "newton"]

    public static func forbiddenUnitsPresent(in text: String) -> [String] {
        let lower = text.lowercased()
        return forbiddenUnits.filter { lower.contains($0) }
    }
}

/// Catches text whose polarity contradicts the measurement behind it.
///
/// This guard exists because of a specific observed failure. Given
/// `COM path: reference 11.13, attempt 6.94` with no indication of which
/// direction is good, the on-device model wrote **"Attempt Lagging Behind
/// Reference"** — for a move where the attempt travelled *less*, i.e. better.
/// The numbers were real and `NumberGuard` passed them; the conclusion drawn
/// from them was backwards.
///
/// `FindingComposer` decides polarity in Swift from `MetricKind.lowerIsBetter`.
/// This checks that whatever prose comes back still agrees with it.
public enum DirectionGuard {
    /// Words that assert the climber did worse than the reference.
    static let worseTerms = [
        "lagging", "behind", "worse", "poorer", "weaker", "less efficient",
        "inefficient", "struggled", "failed to", "needs improvement", "suboptimal"
    ]
    /// Words that assert the climber did better.
    static let betterTerms = [
        "better than", "more efficient", "outperform", "improved on", "stronger than",
        "cleaner than", "tighter than", "beat the"
    ]

    /// Returns a reason when the prose contradicts `attemptIsWorse`, else `nil`.
    public static func violation(in text: String, attemptIsWorse: Bool) -> String? {
        let lower = text.lowercased()
        let saysWorse = worseTerms.contains { lower.contains($0) }
        let saysBetter = betterTerms.contains { lower.contains($0) }

        if attemptIsWorse && saysBetter && !saysWorse {
            return "the text credits the climber on a move where the measurement says they did worse"
        }
        if !attemptIsWorse && saysWorse && !saysBetter {
            return "the text criticises the climber on a move where the measurement says they did better"
        }
        return nil
    }
}

/// Pose data does not contain the climber's mental state, so no output may
/// claim to know it.
public enum SpeculationGuard {
    public static let forbiddenTerms = [
        "scared", "afraid", "fear", "nervous", "anxious", "panic", "confidence",
        "confident", "hesitant", "committed", "commitment", "psyched", "doubt",
        "intimidated", "brave", "courage", "mentally", "mindset", "willpower",
        "gave up", "wanted it", "motivation", "focus", "focussed", "focused"
    ]

    public static func violations(in text: String) -> [String] {
        let lower = text.lowercased()
        return forbiddenTerms.filter { lower.contains($0) }
    }
}
